version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobackend
    ports:
      - '3000:3000'
    restart: unless-stopped
    networks:
      - apinet
      - gateway
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=your_username
      - DATABASE_PASSWORD=your_password
      - DATABASE_NAME=your_database
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: postgres
    restart: unless-stopped
    networks:
      - apinet
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  cache:
  chdata:
  pgdata:
  rdsdata:

networks:
  apinet:
    name: apinet
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.32.0/24"
  gateway:
    name: gateway
    driver: bridge
