import { User } from '../entity/user.entity';
import { UserType } from '../types/user.type';

export const toUserType = (user: User): UserType => {
  const {
    id,
    nickname,
    balance,
    registrationDate,
    referals,
    referer,
    tgUserdata,
    ownedSlideObstacles,
    ownedWagons,
    ownedJumpObstacles,
    ownedRoads,
    ownedSkins,
    personalRecord,
    completedTaskIds,
    earnedMoney,
    earnedByReferer,
    admin,
  } = user;
  return {
    id,
    nickname,
    balance,
    registrationDate,
    referals,
    referer,
    tgUserdata,
    ownedSlideObstacles,
    ownedWagons,
    ownedJumpObstacles,
    ownedRoads,
    ownedSkins,
    personalRecord,
    completedTaskIds,
    earnedMoney,
    earnedByReferer,
    admin,
    selectedSkin: '',
    selectedJumpObstacle: '',
    selectedRoad: '',
    selectedSlideObstacle: '',
    selectedWagon: '',
    settings: '',
    energy: 10,
    lastUpdated: Date.now(),
  };
};
