apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobackend
  template:
    metadata:
      labels:
        app: mobackend
    spec:
      containers:
        - name: mobackend
          image: yourusername/mobackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: DATABASE_NAME
              value: your_database
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: secret
