apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobackend-deployment
  namespace: yandex-system  # Добавляем пространство имен
  labels:
    app: mobackend
spec:
  replicas: 2  # Увеличиваем количество реплик до 3
  selector:
    matchLabels:
      app: mobackend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Указываем, что все поды должны быть доступны во время обновления
      maxSurge: 1  # Можно запустить один дополнительный под во время обновления
  template:
    metadata:
      labels:
        app: mobackend
    spec:
      containers:
        - name: mobackend
          image: andreyzuikov/mobackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis_connection
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis_host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis_password
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: redis_port
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_port
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_name
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: bot_token
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt_secret

          readinessProbe:
            httpGet:
              path: /api-docs
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api-docs
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3