apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobackend-deployment
  labels:
    app: mobackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobackend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mobackend
    spec:
      containers:
        - name: mobackend
          image: andreyzuikov/mobackend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              value: "postgres-service"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DATABASE_NAMES
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRET
      volumes:
        - name: cache
          emptyDir: {}
        - name: chdata
          emptyDir: {}
        - name: rdsdata
          emptyDir: {}