apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database_user: <base64_encoded_value>
  database_password: <base64_encoded_value>
  database_name: <base64_encoded_value>

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
type: Opaque
data:
  jwt_secret: <base64_encoded_value>
