apiVersion: v1
kind: Service
metadata:
  name: mobackend-service
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: mobackend
  ports:
    - nodePort: 30000
      port: 3000
      protocol: TCP
      targetPort: 80
