apiVersion: v1
kind: Service
metadata:
  name: mobackend-service
spec:
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  type: NodePort
  selector:
    app: mobackend
  ports:
    - nodePort: 30000
      port: 3000
      protocol: TCP
      targetPort: 80
