name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t andreyzuikov/mobackend:${{ env.sha }} .
          docker push andreyzuikov/mobackend:${{ env.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Setup protected regular
        run: sudo sysctl fs.protected_regular=0

      - name: Connect to Remote VM and Deploy to Kubernetes
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Pull latest code from repository
            cd mobackend
            git pull

            # Update the deployment YAML with the new Docker image tag
            sed -i "s|image: andreyzuikov/mobackend:.*|image: andreyzuikov/mobackend:${{ env.sha }}|" /home/andrey/mobackend/k8s/deployment.yaml

            # Apply the updated Kubernetes manifests
            kubectl apply -f /home/andrey/mobackend/k8s/deployment.yaml
            kubectl apply -f /home/andrey/mobackend/k8s/postgres-deployment.yaml
            kubectl apply -f /home/andrey/mobackend/k8s/postgres-service.yaml
            kubectl apply -f /home/andrey/mobackend/k8s/pvc.yaml
            kubectl apply -f /home/andrey/mobackend/k8s/service.yaml
