name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать тесты при открытии PR в main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t andreyzuikov/mobackend:latest .
          docker push andreyzuikov/mobackend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd mobackend
            sudo docker pull andreyzuikov/mobackend:latest
            # Start rolling update by first scaling up the service
            sudo docker compose up -d --no-deps --scale app=2
            # Gracefully remove the old container
            sudo docker compose stop app --timeout 30
            sudo docker compose rm -f app
            # Scale back to original size
            sudo docker compose up -d --no-deps --scale app=1
