name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t andreyzuikov/mobackend:latest .
          docker push andreyzuikov/mobackend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Connect to Remote VM and Install Minikube and kubectl
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Install kubectl if not already installed
            if ! command -v kubectl &> /dev/null; then
              sudo snap install kubectl --classic
            fi

            # Install Minikube if not already installed
            if ! command -v minikube &> /dev/null; then
              curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
              sudo install minikube-linux-amd64 /usr/local/bin/minikube
            fi

            # Start Minikube if not running
            if ! minikube status &>/dev/null; then
              sudo minikube start --force
            fi

            # Set up Docker environment to use Minikube's Docker daemon
            eval $(minikube -p minikube docker-env)
            
            # Update kubeconfig for Minikube
            sudo minikube update-context

      - name: Copy Kubernetes Manifests to Remote VM
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.SERVER_USER }}/mobackend/k8s
          upload: |
            scp -i ${{ secrets.SERVER_SSH_KEY }} -r ./k8s ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/mobackend/

      - name: Deploy to Minikube
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo kubectl apply -f /home/${{ secrets.SERVER_USER }}/mobackend/k8s/secret.yaml --validate=false
            sudo kubectl apply -f /home/${{ secrets.SERVER_USER }}/mobackend/k8s/postgres-deployment.yaml --validate=false
            sudo kubectl apply -f /home/${{ secrets.SERVER_USER }}/mobackend/k8s/postgres-service.yaml --validate=false
            sudo kubectl apply -f /home/${{ secrets.SERVER_USER }}/mobackend/k8s/deployment.yaml --validate=false
            sudo kubectl apply -f /home/${{ secrets.SERVER_USER }}/mobackend/k8s/service.yaml --validate=false
