name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t andreyzuikov/mobackend:latest .
          docker push andreyzuikov/mobackend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Setup protected regular
        run: sudo sysctl fs.protected_regular=0

      - name: Connect to Remote VM and Install Minikube, kubectl, and cri-dockerd
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Install kubectl if not already installed
            if ! command -v kubectl &> /dev/null; then
              sudo snap install kubectl --classic
            fi

            # Install Docker if not already installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            # Install Minikube if not already installed
            if ! command -v minikube &> /dev/null; then
              curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
              sudo install minikube-linux-amd64 /usr/local/bin/minikube
            fi

            # Install cri-dockerd if not already installed
            if ! command -v cri-dockerd &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y git golang-go
              git clone https://github.com/Mirantis/cri-dockerd.git
              cd cri-dockerd
              mkdir bin
              go build -o bin/cri-dockerd
              sudo install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd
              sudo cp -a packaging/systemd/* /etc/systemd/system/
              sudo sed -i s:/usr/bin:/usr/local/bin/: /etc/systemd/system/cri-docker.service
              sudo systemctl daemon-reload
              sudo systemctl enable cri-docker.service
              sudo systemctl enable --now cri-docker.socket
            fi

            # Start Minikube with the Docker driver
            if ! minikube status &>/dev/null; then
              minikube start --driver=none --force
            fi

            # Wait for Minikube to be fully started
            sleep 120

            # Set up Docker environment to use Minikube's Docker daemon
            eval $(minikube -p minikube docker-env)

            # Update kubeconfig for Minikube
            minikube update-context
